## 처음 세팅 시에만

In [ ]:
# Google Drive 마운트
from google.colab import drive
drive.mount('/content/drive')

%cd /content/drive/MyDrive/B.S.degree

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/MyDrive/B.S.degree

In [ ]:
import os
from google.colab import userdata
os.environ['GITHUB_TOKEN'] = userdata.get('GITHUB_TOKEN')

!git config --global credential.helper store
!git config --global user.email "modifymeter@naver.com"
!git config --global user.name "Hwaaanss"

# 1. GitHub 레포지토리 주소 설정
## %env REPO_URL=https://{github_id}:{personal_access_token}@github.com/{github_id}/test.git
REPO_URL = f"https://Hwaaanss:{os.environ['GITHUB_TOKEN']}@github.com/Hwaaanss/Capstone2_HelloKitty.git"

# 2. 레포지토리 클론 (이미 클론했다면 생략)
!git clone {REPO_URL}

# 3. 클론된 레포지토리 폴더로 이동
# %cd {repository_name}
%cd Capstone2_HelloKitty

# 4. Git LFS 설치 및 설정 (최초 한 번만 실행)
!git lfs install

# 5. Git LFS로 관리할 파일 확장자 지정 (예: .pth, .h5, .pt 등 모델 가중치 파일)
!git lfs track "*.pth"
!git lfs track "*.h5"

# 6. .gitattributes 파일이 생성되었는지 확인하고, 이 파일을 커밋 대상에 추가
!git add .gitattributes

# 7. 변경된 모든 파일을 스테이징(Staging) 영역에 추가
!git add .

# 8. 변경 사항에 대한 메시지와 함께 커밋
!git commit -m "Colab 노트북과 모델 가중치 추가"

# 9. GitHub 레포지토리로 푸시
!git push --no-verify

env: REPO_URL=https://Hwaaanss:$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@github.com/Hwaaanss/Capstone2_HelloKitty.git
fatal: destination path 'Capstone2_HelloKitty' already exists and is not an empty directory.
/content/drive/MyDrive/B.S.degree/Capstone2_HelloKitty
Updated git hooks.
Git LFS initialized.
"*.pth" already supported
"*.h5" already supported

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
Everything up-to-date

## 이후 작업 시

In [1]:
# Google Drive 마운트
from google.colab import drive
drive.mount('/content/drive')

%cd /content/drive/MyDrive/B.S.degree

Mounted at /content/drive
/content/drive/MyDrive/B.S.degree

In [2]:
import os
from google.colab import userdata
os.environ['GITHUB_TOKEN'] = userdata.get('GITHUB_TOKEN')

!git config --global credential.helper store
!git config --global user.email "modifymeter@naver.com"
!git config --global user.name "Hwaaanss"

# 1. GitHub 레포지토리 주소 설정
## %env REPO_URL=https://{github_id}:{personal_access_token}@github.com/{github_id}/test.git
REPO_URL = f"https://Hwaaanss:{os.environ['GITHUB_TOKEN']}@github.com/Hwaaanss/Capstone2_HelloKitty.git"

# 2. 레포지토리 클론 (버전 꼬이는걸 방지하기 위해 매번 실행하는거 추천)
!git clone {REPO_URL}

fatal: destination path 'Capstone2_HelloKitty' already exists and is not an empty directory.

In [3]:
# 3. 클론된 레포지토리 폴더로 이동
## %cd {repository_name}
%cd Capstone2_HelloKitty

# 4. Git LFS 설치 및 설정
!git lfs install

# 5. Git LFS로 관리할 파일 확장자 지정 (예: .pth, .h5, .pt 등 모델 가중치 파일들도 커밋하려면 추가 후 6번으로 반영)
## !git lfs track "*.{확장자명}"

# 6. .gitattributes 파일이 생성되었는지 확인하고, 이 파일을 커밋 대상에 추가
## !git add .gitattributes

/content/drive/MyDrive/B.S.degree/Capstone2_HelloKitty
mkdir /dev/null: not a directory
To resolve this, either:
  1: run `git lfs update --manual` for instructions on how to merge hooks.
  2: run `git lfs update --force` to overwrite your hook.

In [ ]:
## 버젼 꼬이면 깃허브 기준으로 병합해오기
!git pull origin main --no-rebase --no-edit

From https://github.com/Hwaaanss/Capstone2_HelloKitty
 * branch            main       -> FETCH_HEAD
Already up to date.

In [ ]:
####### 작업 후
# 변경된 모든 파일을 스테이징(Staging) 영역에 추가
!git add .

# 변경 사항에 대한 메시지와 함께 커밋
!git commit -m "delete unnecessary files"

# GitHub 레포지토리로 푸시
!git push --no-verify

#### 강제 push

In [ ]:
#### 강제 push
# 진행 중인 rebase/merge를 포기
!git rebase --abort
!git merge --abort   # merge 도중이면

# 로컬 변경 사항을 강제로 원격에 올림
!git add .
!git commit -m "로컬 변경 강제 반영"
!git push origin main --force

fatal: No rebase in progress?
fatal: There is no merge to abort (MERGE_HEAD missing).
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
Everything up-to-date

## Data Preprocessing

In [ ]:
import gc
import math
import calendar
from datetime import datetime
import pandas as pd

In [ ]:
data1 = pd.read_csv('/content/drive/MyDrive/B.S.degree/Capstone2_HelloKitty/dataset/big_data_set1_f.csv', encoding='cp949')
data2 = pd.read_csv('/content/drive/MyDrive/B.S.degree/Capstone2_HelloKitty/dataset/big_data_set2_f.csv', encoding='cp949')
data3 = pd.read_csv('/content/drive/MyDrive/B.S.degree/Capstone2_HelloKitty/dataset/big_data_set3_f.csv', encoding='cp949')

data = pd.merge(data2, data3, on=['ENCODED_MCT' ,'TA_YM'], how='inner')
data = pd.merge(data, data1, on='ENCODED_MCT', how='left')

del data1, data2, data3
gc.collect()

data

,ENCODED_MCT,TA_YM,MCT_OPE_MS_CN,RC_M1_SAA,RC_M1_TO_UE_CT,RC_M1_UE_CUS_CN,RC_M1_AV_NP_AT,APV_CE_RAT,DLV_SAA_RAT,M1_SME_RY_SAA_RAT,...,RC_M1_SHC_WP_UE_CLN_RAT,RC_M1_SHC_FLP_UE_CLN_RAT,MCT_BSE_AR,MCT_NM,MCT_BRD_NUM,MCT_SIGUNGU_NM,HPSN_MCT_ZCD_NM,HPSN_MCT_BZN_CD_NM,ARE_D,MCT_ME_D
0,000F03E44A,202404,4_50-75%,5_75-90%,5_75-90%,5_75-90%,5_75-90%,1_상위1구간,-999999.9,2.6,...,12.5,75.0,서울특별시 성동구 왕십리로4가길 9,육육**,NaN,서울 성동구,중식-딤섬/중식만두,뚝섬,20220225,NaN
1,000F03E44A,202312,4_50-75%,6_90%초과(하위 10% 이하),6_90%초과(하위 10% 이하),6_90%초과(하위 10% 이하),6_90%초과(하위 10% 이하),NaN,-999999.9,0.0,...,-999999.9,-999999.9,서울특별시 성동구 왕십리로4가길 9,육육**,NaN,서울 성동구,중식-딤섬/중식만두,뚝섬,20220225,NaN
2,002816BA73,202404,2_10-25%,3_25-50%,4_50-75%,4_50-75%,2_10-25%,6_상위6구간(하위1구간),-999999.9,96.6,...,23.8,52.4,서울 성동구 청계천로10나길 78,자갈***********,NaN,서울 성동구,요리주점,마장동,20140507,NaN
3,002816BA73,202411,2_10-25%,3_25-50%,4_50-75%,4_50-75%,2_10-25%,6_상위6구간(하위1구간),-999999.9,108.0,...,11.5,76.9,서울 성동구 청계천로10나길 78,자갈***********,NaN,서울 성동구,요리주점,마장동,20140507,NaN
4,002816BA73,202406,2_10-25%,4_50-75%,4_50-75%,4_50-75%,2_10-25%,1_상위1구간,-999999.9,74.2,...,17.4,69.6,서울 성동구 청계천로10나길 78,자갈***********,NaN,서울 성동구,요리주점,마장동,20140507,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86585,A2D9C941A9,202304,5_75-90%,2_10-25%,1_10%이하,1_10%이하,6_90%초과(하위 10% 이하),2_상위2구간,2.6,249.7,...,4.3,24.4,서울특별시 성동구 행당로5길 2,메가***********,커피전문점2,서울 성동구,커피전문점,NaN,20220823,NaN
86586,A7C2307794,202303,2_10-25%,2_10-25%,2_10-25%,2_10-25%,3_25-50%,1_상위1구간,19.2,196.7,...,7.4,55.9,서울 성동구 한림말1길 8.,콩물*****,NaN,서울 성동구,한식-두부요리,옥수,20140508,NaN
86587,BF6A6456AB,202407,6_90%초과(하위 10% 이하),2_10-25%,4_50-75%,4_50-75%,1_10%이하,6_상위6구간(하위1구간),1.6,176.3,...,41.7,41.7,서울특별시 성동구 상원4길 11,우아**,NaN,서울 성동구,한식-육류/고기,뚝섬,20240131,20250724.0
86588,C59F032CAC,202406,1_10%이하,2_10-25%,2_10-25%,2_10-25%,4_50-75%,2_상위2구간,24.0,116.5,...,11.3,48.7,서울 성동구 왕십리로 223-1,밸런***,샌드위치/토스트1,서울 성동구,샌드위치/토스트,한양대,20090421,NaN
86589,F46D45E328,202302,2_10-25%,2_10-25%,3_25-50%,3_25-50%,3_25-50%,1_상위1구간,12.8,215.6,...,25.0,50.0,서울 성동구 용답중앙15길 13.,미*,NaN,서울 성동구,중식당,답십리,20131128,NaN

#### Drop columns

In [ ]:
data['MCT_BRD_NUM'].isnull().sum()

np.int64(74865)

In [ ]:
data['HPSN_MCT_BZN_CD_NM'].isnull().sum()

np.int64(21419)

In [ ]:
data['MCT_SIGUNGU_NM'].value_counts()  ## drop 확정

MCT_SIGUNGU_NM
서울 성동구    86590
Name: count, dtype: int64

In [ ]:
data['MCT_NM'].value_counts()  ## 비식별화 때문에 업종 등 어떠한 정보도 얻을 수 없음.

In [ ]:
data['MCT_BSE_AR'].value_counts()  ## drop 확정

MCT_BSE_AR
서울특별시 성동구 왕십리로 410           1430
서울특별시 성동구 마장로 137             685
서울특별시 성동구 왕십리광장로 17           555
서울  성동구  마장동                  504
서울특별시 성동구 무학로6길 50            399
서울특별시 성동구 무학로 33              279
서울 성동구 살곶이길 18.               278
서울특별시 성동구 자동차시장1길 70          249
서울 성동구 마장로 137.               248
서울 성동구 마조로 17.                240
서울특별시 성동구 마조로 17              203
서울 성동구 마장동                    192
서울특별시 성동구 성수일로10길 26          178
서울특별시 성동구 연무장5가길 25           177
서울특별시 성동구 광나루로6길 35           175
서울특별시 성동구 마장로35길 76           170
서울  성동구  행당동                  168
서울특별시 성동구 동일로 143             161
서울특별시 성동구 행당로 84              156
서울특별시 성동구 왕십리로 222            155
서울  성동구  성수2가1동               144
서울특별시 성동구 아차산로15길 10          141
서울특별시 성동구 마장로37길 40           130
서울특별시 성동구 행당로 87              128
서울특별시 성동구 매봉길 50              122
서울특별시 성동구 마장로31길 43           120
서울  성동구  옥수2동                 120
서울 성동구 마장로35다길 9              120
서울 성동구 성수이로 118.              120
서울특별시 성동구 아차산로 96             118
서울특별시 성동구 행당로 75              117
서울 성동구 성수동2가                  117
서울특별시 성동구 연무장5가길 7            117
서울특별시 성동구 성수이로7길 27           117
서울특별시 성동구 아차산로 49             116
서울특별시 성동구 독서당로40길 39          114
서울특별시 성동구 아차산로7길 36           113
서울특별시 성동구 금호로 173             110
서울특별시 성동구 마장로37길 43           110
서울 성동구 왕십리로 410.              109
서울특별시 성동구 금호로 40              109
서울특별시 성동구 금호로 17              104
서울 성동구 왕십리광장로 17.             103
서울특별시 성동구 용답중앙15길 2           103
서울특별시 성동구 고산자로 284            103
서울특별시 성동구 왕십리로8길 8            100
서울특별시 성동구 마장로31길 40           100
서울특별시 성동구 마조로 30               99
서울  성동구  성수1가1동                96
서울 성동구 마장로37길 43               96
서울특별시 성동구 고산자로14길 26           96
서울특별시 성동구 마장로31가길 5            96
서울 성동구 마조로 17                  96
서울 성동구 고산자로 293.               96
서울특별시 성동구 행당로 79               96
서울 성동구 고산자로24길 6.              96
서울 성동구 마장로37길 59               96
서울특별시 성동구 독서당로 194             96
서울특별시 성동구 마장로37길 53-2          96
서울특별시 성동구 마조로1길 39             94
서울특별시 성동구 성수이로 51              93
서울특별시 성동구 왕십리로21길 11           89
서울특별시 성동구 용답중앙15길 3            88
서울특별시 성동구 행당로1길 7              88
서울 성동구 무학로 33.                 87
서울 성동구 성수일로8길 5.               86
서울특별시 성동구 상원1길 26              85
서울특별시 성동구 마장로 310              85
서울특별시 성동구 왕십리로 108             85
서울특별시 성동구 고산자로 177             85
서울특별시 성동구 왕십리로 58              84
서울특별시 성동구 성수이로 118             84
서울특별시 성동구 서울숲2길 32-14          82
서울특별시 성동구 성덕정9가길 2             82
서울특별시 성동구 연무장7길 7-1            80
서울특별시 성동구 성수이로 147             80
서울특별시 성동구 상원2길 1-10            79
서울특별시 성동구 독서당로 223             78
서울특별시 성동구 무학봉28길 4-1           77
서울특별시 성동구 왕십리로20길 8            77
서울특별시 성동구 금호로 105              76
서울 성동구 무학로6길 50.               76
서울특별시 성동구 왕십리로4길 13-1          76
서울특별시 성동구 금호로 102              75
서울특별시 성동구 아차산로7길 7             74
서울특별시 성동구 성수일로8길 5             74
서울특별시 성동구 마장로 203-1            73
서울특별시 성동구 왕십리로 311-1           72
서울특별시 성동구 성수이로7길 1             72
서울 성동구 행당로 87.                 72
서울 성동구 금호로 17.                 72
서울 성동구 마조로 21.                 72
서울특별시 성동구 상원길 40               72
서울 성동구 아차산로 116.               72
서울특별시 성동구 왕십리로4길 28-2          72
서울 성동구 고산자로6길 40.              72
서울특별시 성동구 아차산로 92              72
서울 성동구 고산자로24길 11-1            72
서울특별시 성동구 고산자로2길 67            72
서울 성동구 행당로 129.                72
서울특별시 성동구 성수일로 47              72
서울특별시 성동구 금호산길 66-1            72
서울특별시 성동구 성수일로 10              72
서울  성동구  성수2가3동                72
서울특별시 성동구 연무장길 41-22           72
서울특별시 성동구 마조로3길 8              72
서울특별시 성동구 독서당로 270             72
서울 성동구 성수이로7길 27.              72
서울  성동구  금호동1가                 72
서울특별시 성동구 성수이로7길 7             72
서울특별시 성동구 장터길 35               72
서울특별시 성동구 아차산로7나길 18           72
서울  성동구  성수1가2동                72
서울 성동구 성수일로4길 25.              72
서울특별시 성동구 뚝섬로 385-40           72
서울  성동구  행당1동                  72
서울특별시 성동구 뚝섬로 341-18           72
서울특별시 성동구 독서당로 187             72
서울 성동구 성수일로 77.                72
서울  성동구  금호동3가                 72
서울특별시 성동구 아차산로13길 31           72
서울특별시 성동구 마장로31길 44            72
서울특별시 성동구 상원2길 5-5             72
서울특별시 성동구 고산자로24길 18           72
서울 성동구 마조로1길 2.                72
서울  성동구  상원길                   72
서울특별시 성동구 마장로37길 45            72
서울 성동구 광나루로6길 35.              72
서울특별시 성동구 독서당로39길 43-1         72
서울특별시 성동구 용답중앙15길 14           72
서울특별시 성동구 마장로 301              72
서울 성동구 사근동길 68.                72
서울 성동구 왕십리로21길 17.             72
서울특별시 성동구 왕십리로 357             71
서울특별시 성동구 아차산로7길 4             70
서울 성동구 성수이로 45.                68
서울특별시 성동구 왕십리로24길 18           67
서울특별시 성동구 마장로35나길 40           67
서울특별시 성동구 성수일로 9               67
서울특별시 성동구 행당로 112              67
서울특별시 성동구 광나루로 130             66
서울특별시 성동구 상원2길 1               66
서울특별시 성동구 연무장15길 11            65
서울특별시 성동구 아차산로1길 9             64
서울특별시 성동구 금호산길 49-1            64
서울특별시 성동구 독서당로 381             62
서울 성동구 연무장5가길 7.               62
서울특별시 성동구 연무장길 60              62
서울특별시 성동구 한림말길 31              62
서울특별시 성동구 아차산로 126             61
서울특별시 성동구 성덕정17길 11            61
서울특별시 성동구 마장로37길 49            60
서울특별시 성동구 금호산길 71              59
서울특별시 성동구 고산자로24길 15           59
서울특별시 성동구 마장로35길 46            59
서울특별시 성동구 성수일로8길 53            58
서울특별시 성동구 마조로 59               58
서울특별시 성동구 고산자로6길 40            57
서울특별시 성동구 성수일로4길 37            57
서울특별시 성동구 마조로1길 41             57
서울 성동구 고산자로24길 11              56
서울특별시 성동구 왕십리광장로 6             56
서울 성동구 마장로37길 40               56
서울특별시 성동구 무학봉길 54-1            55
서울특별시 성동구 성덕정길 127             55
서울특별시 성동구 아차산로11길 11           55
서울특별시 성동구 연무장길 41-26           55
서울특별시 성동구 왕십리로 336             55
서울특별시 성동구 용답19길 18-1           55
서울특별시 성동구 무수막길 85              54
서울특별시 성동구 왕십리로20길 43           54
서울특별시 성동구 무학봉15길 26-1          53
서울특별시 성동구 성수이로7가길 6            53
서울특별시 성동구 상원12길 30             53
서울특별시 성동구 성덕정17길 4             52
서울특별시 성동구 상원10길 3              52
서울특별시 성동구 무학로2길 48             52
서울특별시 성동구 왕십리로4길 26-18         51
서울특별시 성동구 상원길 19               51
서울특별시 성동구 마조로 27               51
서울특별시 성동구 왕십리로5길 9-20          51
서울특별시 성동구 마장로23길 7             50
서울특별시 성동구 왕십리로4길 10-12         50
서울특별시 성동구 마장로35다길 9            50
서울특별시 성동구 마조로 25               50
서울특별시 성동구 성수일로 99              49
서울특별시 성동구 성수일로8길 42            49
서울특별시 성동구 연무장길 114             49
서울특별시 성동구 고산자로24길 11-1         48
서울 성동구 행당동                     48
서울특별시 성동구 성수이로12길 8            48
서울특별시 성동구 성수이로14길 7            48
서울  성동구  홍익동                   48
서울특별시 성동구 동일로 75               48
서울 성동구 성수일로8길 47.              48
서울 성동구 마조로 19-10.              48
서울특별시 성동구 왕십리로21길 39-1         48
서울 성동구 아차산로11길 26.             48
서울 성동구 성수일로12길 27.             48
서울특별시 성동구 상원2길 5-11            48
서울 성동구 아차산로11길 11              48
서울 성동구 아차산로13길 48.             48
서울특별시 성동구 왕십리로 257             48
서울특별시 성동구 둘레9가길 36             48
서울  성동구  하왕십리2동                48
서울특별시 성동구 상원6길 8               48
서울 성동구 용답중앙15길 13.             48
서울특별시 성동구 뚝섬로 390              48
서울 성동구 성수일로4길 45.              48
서울특별시 성동구 왕십리로24길 12           48
서울특별시 성동구 마장로 283              48
서울 성동구 매봉길 2.                  48
서울특별시 성동구 마조로3가길 30            48
서울특별시 성동구 장터길 27-2             48
서울 성동구 왕십리로21길 20.             48
서울특별시 성동구 왕십리로31나길 21          48
서울특별시 성동구 왕십리로 309             48
서울 성동구 왕십리로24길 12.             48
서울특별시 성동구 용답19길 5              48
서울특별시 성동구 아차산로 135             48
서울특별시 성동구 사근동길 61              48
서울 성동구 성덕정길 120.               48
서울특별시 성동구 마조로7길 14             48
서울특별시 성동구 고산자로20길 9            48
서울  성동구  송정동                   48
서울특별시 성동구 왕십리로4길 28-8          48
서울 성동구 왕십리로 291-2              48
서울특별시 성동구 독서당로 297-3           48
서울특별시 성동구 연무장길 94              48
서울특별시 성동구 용답중앙15길 17           48
서울특별시 성동구 뚝섬로 400              48
서울특별시 성동구 무학봉길 64-4            48
서울 성동구 성수일로12길 25.             48
서울 성동구 용답25라길 23               48
서울특별시 성동구 한림말5길 11             48
서울  성동구  용답동                   48
서울 성동구 뚝섬로 404                 48
서울 성동구 아차산로 87                 48
서울특별시 성동구 서울숲4길 28             48
서울 성동구 성덕정15길 5                48
서울특별시 성동구 청계천로10가길 38          48
서울 성동구 행당로 84.                 48
서울특별시 성동구 연무장7가길 9             48
서울특별시 성동구 마장로 297              48
서울 성동구 마조로 29.                 48
서울 성동구 독서당로40길 33.             48
서울 성동구 무학로2길 36.               48
서울 성동구 마조로5길 4-16.             48
서울 성동구 독서당로 160.               48
서울 성동구 광나루로 320-1.             48
서울특별시 성동구 광나루로 320-1           48
서울특별시 성동구 마조로3길 9              48
서울특별시 성동구 아차산로7길 28            48
서울특별시 성동구 성수이로 127             48
서울 성동구 마조로 15-6.               48
서울특별시 성동구 행당로 119-6            48
서울 성동구 성덕정17길 1.               48
서울특별시 성동구 성덕정길 27              48
서울특별시 성동구 왕십리로 114             48
서울특별시 성동구 성수이로14길 15           48
서울특별시 성동구 왕십리로 66-26           48
서울특별시 성동구 마조로 24               48
서울특별시 성동구 독서당로 194-1           48
서울 성동구 금호로3길 18-44             48
서울특별시 성동구 고산자로8길 20            48
서울  성동구  무수막길                  48
서울 성동구 독서당로 314.               48
서울특별시 성동구 연무장17길 5             48
서울특별시 성동구 왕십리로 134             48
서울  성동구  응봉동                   48
서울특별시 성동구 성수일로12길 20           48
서울특별시 성동구 마장로33길 67            48
서울 성동구 성덕정길 95.                48
서울 성동구 마장로 283.                48
서울특별시 성동구 광나루로 290             48
서울 성동구 마조로1길 4.                48
서울특별시 성동구 용답25다길 23            48
서울특별시 성동구 왕십리로22길 10           48
서울 성동구 왕십리로8길 5.               48
서울 성동구 고산자로24길 16              48
서울 성동구 연무장15길 11.              48
서울특별시 성동구 상원길 59               48
서울  성동구  행당2동                  48
서울 성동구 사근동길 4.                 48
서울특별시 성동구 금호산2길 17-1           48
서울특별시 성동구 광나루로11길 50           48
서울 성동구 고산자로24길 14-2.           48
서울특별시 성동구 상원12길 5              48
서울 성동구 금호로 100.                48
서울특별시 성동구 왕십리로2길 34            48
서울 성동구 상원길 39.                 48
서울 성동구 광나루로 290                48
서울특별시 성동구 독서당로 434             48
서울특별시 성동구 행당로 82               48
서울 성동구 고산자로 345.               48
서울특별시 성동구 아차산로 116             48
서울특별시 성동구 광나루로 291             48
서울특별시 성동구 광나루로9길 2             48
서울특별시 성동구 고산자로 306             48
서울특별시 성동구 성수이로26길 47           48
서울 성동구 왕십리로22길 3.              48
서울특별시 성동구 행당로 76               48
서울특별시 성동구 마조로5길 4              48
서울특별시 성동구 성수일로4길 25            48
서울특별시 성동구 왕십리로 347             48
서울특별시 성동구 매봉길 20               48
서울특별시 성동구 독서당로 296-1           48
서울특별시 성동구 한림말3길 21             48
서울특별시 성동구 독서당로 285             48
서울특별시 성동구 왕십리로14길 30-1         48
서울 성동구 장터길 47                  48
서울 성동구 아차산로13길 37.             48
서울 성동구 상원10길 8-1.              48
서울특별시 성동구 성수일로1길 18            48
서울특별시 성동구 용답중앙23길 1            48
서울 성동구 마장로 228.                48
서울특별시 성동구 장터길 38-1             48
서울 성동구 아차산로15길 10.             48
서울특별시 성동구 아차산로7길 22            48
서울특별시 성동구 고산자로 293             48
서울특별시 성동구 연무장7가길 2             48
서울특별시 성동구 마조로5길 4-5            48
서울특별시 성동구 장터길 41               48
서울 성동구 왕십리로21길 17              48
서울특별시 성동구 왕십리로10길 10           48
서울특별시 성동구 서울숲6길 14             48
서울특별시 성동구 왕십리로24길 34           48
서울특별시 성동구 금호산길 59              48
서울특별시 성동구 성덕정길 93              48
서울특별시 성동구 아차산로13길 33           48
서울특별시 성동구 성덕정길 82-1            48
서울특별시 성동구 마장로35나길 3-60         48
서울특별시 성동구 용답중앙21길 1            48
서울특별시 성동구 성수일로4길 46            48
서울 성동구 고산자로 281.               48
서울 성동구 성덕정길 109.               48
서울 성동구 마조로7길 5.                48
서울 성동구 뚝섬로 392.                48
서울 성동구 상원길 24.                 48
서울특별시 성동구 장터길 35-1             48
서울특별시 성동구 왕십리로24길 5            48
서울특별시 성동구 독서당로40길 37           48
서울 성동구 마장로31가길 5.              48
서울특별시 성동구 아차산로7길 15            48
서울 성동구 아차산로7길 10-1.            48
서울 성동구 연무장7길 12.               48
서울특별시 성동구 성수일로4가길 2            48
서울특별시 성동구 아차산로17길 57           48
서울특별시 성동구 왕십리로22길 6            48
서울 성동구 마장로37길 53.              48
서울 성동구 상왕십리동                   48
서울특별시 성동구 성덕정길 72-4            48
서울특별시 성동구 용답중앙13길 1            48
서울특별시 성동구 아차산로3길 9             48
서울특별시 성동구 연무장5가길 26            48
서울  성동구  마장로  305              48
서울특별시 성동구 성수이로12길 13           48
서울 성동구 독서당로 187.               48
서울특별시 성동구 서울숲2길 19-13          48
서울특별시 성동구 성수이로 126             48
서울 성동구 뚝섬로 385-32.             48
서울 성동구 성수일로12길 20.             48
서울 성동구 아차산로17길 26.             48
서울 성동구 아차산로 96.                48
서울특별시 성동구 상원2길 3               48
서울특별시 성동구 아차산로7길 17-1          48
서울 성동구 마조로 33                  48
서울 성동구 성수일로8길 53.              48
서울 성동구 성수일로12길 20              48
서울특별시 성동구 왕십리로 102             48
서울특별시 성동구 성수일로3길 5-12          48
서울 성동구 용답동                     48
서울특별시 성동구 연무장길 81              48
서울 성동구 연무장7길 16.               48
서울 성동구 마장로27가길 27-6.           48
서울특별시 성동구 무학봉15길 28-1          48
서울특별시 성동구 고산자로10길 8            48
서울특별시 성동구 뚝섬로 385-32           48
서울특별시 성동구 고산자로24길 11           48
서울특별시 성동구 연무장5가길 20            48
서울 성동구 사근동길 59.                48
서울특별시 성동구 뚝섬로 395              48
서울특별시 성동구 마조로 15-3             48
서울 성동구 행당로17길 5                48
서울 성동구 성수이로 108.               48
서울특별시 성동구 무학로2길 41             48
서울특별시 성동구 아차산로7길 29            48
서울 성동구 마장로31길 40.              48
서울 성동구 아차산로13길 37              48
서울특별시 성동구 성수일로8길 39            48
서울특별시 성동구 동호로 21               48
서울 성동구 금호로 127 .               48
서울 성동구 마장로37길 59.              48
서울특별시 성동구 연무장7길 4              48
서울 성동구 동일로 83                  48
서울 성동구 홍익동                     48
서울  성동구  금호동4가                 48
서울 성동구 동일로 143.                48
서울 성동구 마조로 25.                 48
서울 성동구 서울숲2길 46-9.             48
서울 성동구 동일로 143 .               48
서울특별시 성동구 금호로 145              48
서울특별시 성동구 성수일로1길 10            48
서울 성동구 고산자로24길 11.             48
서울 성동구 성덕정17길 8-1              48
서울특별시 성동구 마조로16길 23            48
서울특별시 성동구 고산자로 164             48
서울특별시 성동구 왕십리로4길 24-7          47
서울특별시 성동구 뚝섬로17가길 48           47
서울특별시 성동구 왕십리로5길 19            47
서울특별시 성동구 용답15길 14             47
서울특별시 성동구 서울숲2길 14             47
서울특별시 성동구 성덕정17길 7             46
서울특별시 성동구 왕십리로 328             46
서울특별시 성동구 금호산길 56-1            46
서울 성동구 왕십리로 410 .              46
서울특별시 성동구 무학봉15다길 4            46
서울특별시 성동구 장터길 13-1             46
서울특별시 성동구 한림말5길 17             46
서울특별시 성동구 마조로3길 7-1            46
서울특별시 성동구 왕십리로24길 3            46
서울특별시 성동구 뚝섬로1길 31             45
서울특별시 성동구 광나루로 302             45
서울특별시 성동구 성수일로4길 45            45
서울특별시 성동구 마장로35다길 16           45
서울특별시 성동구 독서당로60길 2            45
서울특별시 성동구 아차산로7길 20            44
서울특별시 성동구 성덕정17길 9             44
서울특별시 성동구 고산자로2길 65            44
서울특별시 성동구 상원1길 35-14           44
서울특별시 성동구 독서당로 295-1           44
서울특별시 성동구 고산자로 281             43
서울특별시 성동구 고산자로6가길 21           43
서울특별시 성동구 성덕정3길 8              43
서울특별시 성동구 성수일로 95              43
서울특별시 성동구 성수일로11길 11           43
서울특별시 성동구 광나루로 144             43
서울특별시 성동구 독서당로 336             43
서울특별시 성동구 뚝섬로9길 13-1           43
서울특별시 성동구 무학봉15길 17-1          43
서울특별시 성동구 아차산로13길 37           42
서울특별시 성동구 마장로 216              42
서울특별시 성동구 왕십리로10길 9-31         42
서울특별시 성동구 왕십리로4길 26-7          42
서울특별시 성동구 마장로26길 16-1          42
서울특별시 성동구 성수이로10길 14           42
서울특별시 성동구 아차산로17길 48           42
서울특별시 성동구 아차산로13길 16           42
서울특별시 성동구 동일로 41               41
서울특별시 성동구 자동차시장1길 39           41
서울특별시 성동구 아차산로 113             41
서울특별시 성동구 뚝섬로11길 21            41
서울특별시 성동구 연무장길 41-19           41
서울특별시 성동구 아차산로7길 18            41
서울특별시 성동구 서울숲2길 13             41
서울특별시 성동구 성수일로8길 40            41
서울특별시 성동구 금호로 148-1            41
서울특별시 성동구 무학봉16길 24-2          40
서울특별시 성동구 서울숲2길 2              40
서울특별시 성동구 천호대로 294             40
서울특별시 성동구 금호로 127              40
서울특별시 성동구 마장로 271              40
서울특별시 성동구 고산자로 354             40
서울특별시 성동구 독서당로 329             40
서울특별시 성동구 광나루로11길 17-1         40
서울특별시 성동구 독서당로39길 48           40
서울특별시 성동구 금호로 80-1             39
서울특별시 성동구 무학로6길 33             39
서울특별시 성동구 성수이로 35              39
서울특별시 성동구 용답29길 26             39
서울특별시 성동구 아차산로 153             39
서울특별시 성동구 금호로 58               39
서울특별시 성동구 성수이로20길 10           39
서울특별시 성동구 둘레15길 11             39
서울특별시 성동구 금호로 151              38
서울특별시 성동구 독서당로 296-11          38
서울특별시 성동구 연무장7길 7              38
서울특별시 성동구 무학봉26길 2             38
서울특별시 성동구 금호로 141-2            38
서울특별시 성동구 뚝섬로 312              38
서울특별시 성동구 독서당로 295-5           38
서울특별시 성동구 마조로3가길 10            38
서울특별시 성동구 마조로 21               38
서울특별시 성동구 동일로 75-18            38
서울특별시 성동구 뚝섬로3길 16             38
서울특별시 성동구 연무장길 9-1             38
서울특별시 성동구 상원10길 25             38
서울특별시 성동구 서울숲4길 26-10          38
서울특별시 성동구 왕십리로21길 10-1         38
서울특별시 성동구 뚝섬로7길 6              37
서울특별시 성동구 무학봉길 41-1            37
서울특별시 성동구 행당로 121              37
서울특별시 성동구 무학봉16길 26-9          37
서울특별시 성동구 왕십리로10길 9-9          37
서울특별시 성동구 마장로35다길 18           37
서울특별시 성동구 성덕정길 99              37
서울특별시 성동구 뚝섬로 408-7            37
서울특별시 성동구 왕십리로 136             37
서울특별시 성동구 난계로 35               37
서울특별시 성동구 사근동길 67              36
서울특별시 성동구 고산자로 201             36
서울특별시 성동구 마조로1가길 1             36
서울특별시 성동구 왕십리로8길 21            36
서울특별시 성동구 연무장19길 18            36
서울특별시 성동구 독서당로 177             36
서울특별시 성동구 무학봉길 83              36
서울특별시 성동구 왕십리로 80-1            36
서울특별시 성동구 사근동길 4               35
서울특별시 성동구 서울숲길 55              35
서울특별시 성동구 마조로3길 6              35
서울특별시 성동구 고산자로 297             35
서울특별시 성동구 성수이로 18              35
서울특별시 성동구 연무장7길 8-1            35
서울특별시 성동구 왕십리로21길 25           35
서울특별시 성동구 마조로3가길 25            35
서울특별시 성동구 마장로35라길 16           35
서울특별시 성동구 성덕정15길 12            34
서울특별시 성동구 자동차시장1길 30           34
서울특별시 성동구 성수일로12길 26           34
서울특별시 성동구 연무장길 12              34
서울특별시 성동구 행당로17길 27            34
서울특별시 성동구 상원길 17               34
서울특별시 성동구 성덕정15길 6-14          34
서울특별시 성동구 성수이로 66              34
서울특별시 성동구 연무장9길 6              33
서울특별시 성동구 마조로3가길 12            33
서울특별시 성동구 마장로37길 41            33
서울 성동구 마조로3가길 25.              33
서울특별시 성동구 행당로 119              33
서울 성동구 동호로 93 .                33
서울특별시 성동구 뚝섬로 392              33
서울특별시 성동구 성수일로3길 4-13          33
서울 성동구 금호로 62-1.               33
서울특별시 성동구 왕십리로8길 19-4          33
서울특별시 성동구 왕십리로 348             32
서울특별시 성동구 무학봉15길 25            32
서울특별시 성동구 상원10길 4              32
서울특별시 성동구 상원길 48-1             32
서울특별시 성동구 왕십리로4가길 3            32
서울특별시 성동구 용답중앙길 69             32
서울특별시 성동구 아차산로13길 2            32
서울특별시 성동구 용답25다길 24            32
서울특별시 성동구 왕십리로14길 25           32
서울특별시 성동구 아차산로17길 49           31
서울특별시 성동구 연무장길 29-1            31
서울특별시 성동구 한림말3길 27-1           31
서울특별시 성동구 왕십리로10길 18-1         31
서울특별시 성동구 성수이로22길 37           31
서울특별시 성동구 왕십리로8길 19-6          31
서울특별시 성동구 광나루로4길 1-16          31
서울특별시 성동구 금호로 60               30
서울특별시 성동구 왕십리로24나길 8           30
서울특별시 성동구 왕십리로 273-1           30
서울특별시 성동구 연무장길 39-13           30
서울특별시 성동구 행당로 110              30
서울특별시 성동구 행당로 125-4            30
서울특별시 성동구 무수막길 91-1            30
서울특별시 성동구 청계천로10나길 79          30
서울특별시 성동구 장터5길 5               29
서울특별시 성동구 용답중앙길 47-1           29
서울특별시 성동구 용답19길 6              29
서울특별시 성동구 사근동길 6               29
서울특별시 성동구 독서당로 297-2           29
서울특별시 성동구 무학봉16길 3             29
서울특별시 성동구 아차산로7길 41            29
서울특별시 성동구 금호로 84               29
서울특별시 성동구 연무장9길 4              28
서울특별시 성동구 왕십리로4길 16            28
서울특별시 성동구 마조로 15-13            28
서울특별시 성동구 서울숲2길 15             28
서울특별시 성동구 마장로37길 35-1          28
서울특별시 성동구 왕십리로 284             27
서울특별시 성동구 마조로 22               27
서울특별시 성동구 상원12길 34             27
서울특별시 성동구 왕십리로5길 9-16          27
서울특별시 성동구 왕십리로14길 23           27
서울특별시 성동구 왕십리로 340             27
서울특별시 성동구 성덕정길 141             27
서울특별시 성동구 장터길 29-1             27
서울특별시 성동구 광나루로4가길 13           27
서울특별시 성동구 마조로5길 11             27
서울특별시 성동구 무수막길 84              27
서울특별시 성동구 뚝섬로9길 3-1            27
서울특별시 성동구 상원1길 25              26
서울특별시 성동구 왕십리로 363             26
서울특별시 성동구 마조로3가길 18            26
서울특별시 성동구 무학로2길 16             26

In [ ]:
data_prep = data.drop(columns=['MCT_BRD_NUM', 'MCT_SIGUNGU_NM', 'MCT_NM', 'MCT_BSE_AR', 'MCT_BSE_AR'])
data_prep

,ENCODED_MCT,TA_YM,MCT_OPE_MS_CN,RC_M1_SAA,RC_M1_TO_UE_CT,RC_M1_UE_CUS_CN,RC_M1_AV_NP_AT,APV_CE_RAT,DLV_SAA_RAT,M1_SME_RY_SAA_RAT,...,M12_FME_60_RAT,MCT_UE_CLN_REU_RAT,MCT_UE_CLN_NEW_RAT,RC_M1_SHC_RSD_UE_CLN_RAT,RC_M1_SHC_WP_UE_CLN_RAT,RC_M1_SHC_FLP_UE_CLN_RAT,HPSN_MCT_ZCD_NM,HPSN_MCT_BZN_CD_NM,ARE_D,MCT_ME_D
0,000F03E44A,202404,4_50-75%,5_75-90%,5_75-90%,5_75-90%,5_75-90%,1_상위1구간,-999999.9,2.6,...,6.0273,5.00,45.00,12.5,12.5,75.0,중식-딤섬/중식만두,뚝섬,20220225,NaN
1,000F03E44A,202312,4_50-75%,6_90%초과(하위 10% 이하),6_90%초과(하위 10% 이하),6_90%초과(하위 10% 이하),6_90%초과(하위 10% 이하),NaN,-999999.9,0.0,...,0.0000,0.00,0.00,-999999.9,-999999.9,-999999.9,중식-딤섬/중식만두,뚝섬,20220225,NaN
2,002816BA73,202404,2_10-25%,3_25-50%,4_50-75%,4_50-75%,2_10-25%,6_상위6구간(하위1구간),-999999.9,96.6,...,2.2352,10.66,6.12,23.8,23.8,52.4,요리주점,마장동,20140507,NaN
3,002816BA73,202411,2_10-25%,3_25-50%,4_50-75%,4_50-75%,2_10-25%,6_상위6구간(하위1구간),-999999.9,108.0,...,3.3415,10.41,6.30,11.5,11.5,76.9,요리주점,마장동,20140507,NaN
4,002816BA73,202406,2_10-25%,4_50-75%,4_50-75%,4_50-75%,2_10-25%,1_상위1구간,-999999.9,74.2,...,2.0480,9.86,4.69,13.0,17.4,69.6,요리주점,마장동,20140507,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86585,A2D9C941A9,202304,5_75-90%,2_10-25%,1_10%이하,1_10%이하,6_90%초과(하위 10% 이하),2_상위2구간,2.6,249.7,...,4.3371,43.31,10.15,71.3,4.3,24.4,커피전문점,NaN,20220823,NaN
86586,A7C2307794,202303,2_10-25%,2_10-25%,2_10-25%,2_10-25%,3_25-50%,1_상위1구간,19.2,196.7,...,8.5137,19.29,8.75,36.8,7.4,55.9,한식-두부요리,옥수,20140508,NaN
86587,BF6A6456AB,202407,6_90%초과(하위 10% 이하),2_10-25%,4_50-75%,4_50-75%,1_10%이하,6_상위6구간(하위1구간),1.6,176.3,...,5.4627,18.24,12.94,16.7,41.7,41.7,한식-육류/고기,뚝섬,20240131,20250724.0
86588,C59F032CAC,202406,1_10%이하,2_10-25%,2_10-25%,2_10-25%,4_50-75%,2_상위2구간,24.0,116.5,...,1.8656,28.92,7.88,40.0,11.3,48.7,샌드위치/토스트,한양대,20090421,NaN
86589,F46D45E328,202302,2_10-25%,2_10-25%,3_25-50%,3_25-50%,3_25-50%,1_상위1구간,12.8,215.6,...,2.6640,31.16,4.15,25.0,25.0,50.0,중식당,답십리,20131128,NaN

In [ ]:
data_prep.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86590 entries, 0 to 86589
Data columns (total 34 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ENCODED_MCT               86590 non-null  object
 1   TA_YM                     86590 non-null  int64
 2   MCT_OPE_MS_CN             86590 non-null  object
 3   RC_M1_SAA                 86590 non-null  object
 4   RC_M1_TO_UE_CT            86590 non-null  object
 5   RC_M1_UE_CUS_CN           86590 non-null  object
 6   RC_M1_AV_NP_AT            86590 non-null  object
 7   APV_CE_RAT                79958 non-null  object
 8   DLV_SAA_RAT               86590 non-null  float64
 9   M1_SME_RY_SAA_RAT         86590 non-null  float64
 10  M1_SME_RY_CNT_RAT         86590 non-null  float64
 11  M12_SME_RY_SAA_PCE_RT     86590 non-null  float64
 12  M12_SME_BZN_SAA_PCE_RT    86590 non-null  float64
 13  M12_SME_RY_ME_MCT_RAT     86590 non-null  float64
 14  M12_SME_BZN_ME_MCT_RAT    86590 non-null  float64
 15  M12_MAL_1020_RAT          86590 non-null  float64
 16  M12_MAL_30_RAT            86590 non-null  float64
 17  M12_MAL_40_RAT            86590 non-null  float64
 18  M12_MAL_50_RAT            86590 non-null  float64
 19  M12_MAL_60_RAT            86590 non-null  float64
 20  M12_FME_1020_RAT          86590 non-null  float64
 21  M12_FME_30_RAT            86590 non-null  float64
 22  M12_FME_40_RAT            86590 non-null  float64
 23  M12_FME_50_RAT            86590 non-null  float64
 24  M12_FME_60_RAT            86590 non-null  float64
 25  MCT_UE_CLN_REU_RAT        86590 non-null  float64
 26  MCT_UE_CLN_NEW_RAT        86590 non-null  float64
 27  RC_M1_SHC_RSD_UE_CLN_RAT  86590 non-null  float64
 28  RC_M1_SHC_WP_UE_CLN_RAT   86590 non-null  float64
 29  RC_M1_SHC_FLP_UE_CLN_RAT  86590 non-null  float64
 30  HPSN_MCT_ZCD_NM           86590 non-null  object
 31  HPSN_MCT_BZN_CD_NM        65171 non-null  object
 32  ARE_D                     86590 non-null  int64
 33  MCT_ME_D                  2334 non-null   float64
dtypes: float64(23), int64(2), object(9)
memory usage: 22.5+ MB

In [ ]:
columns_to_split = ['MCT_OPE_MS_CN', 'RC_M1_SAA', 'RC_M1_TO_UE_CT','RC_M1_UE_CUS_CN','RC_M1_AV_NP_AT','APV_CE_RAT']

for c in columns_to_split:
    mask = data_prep[c].notna()
    data_prep.loc[mask, c] = data_prep.loc[mask, c].astype(str).str.split('_').str[0].astype(int)
data_prep

,ENCODED_MCT,TA_YM,MCT_OPE_MS_CN,RC_M1_SAA,RC_M1_TO_UE_CT,RC_M1_UE_CUS_CN,RC_M1_AV_NP_AT,APV_CE_RAT,DLV_SAA_RAT,M1_SME_RY_SAA_RAT,...,M12_FME_60_RAT,MCT_UE_CLN_REU_RAT,MCT_UE_CLN_NEW_RAT,RC_M1_SHC_RSD_UE_CLN_RAT,RC_M1_SHC_WP_UE_CLN_RAT,RC_M1_SHC_FLP_UE_CLN_RAT,HPSN_MCT_ZCD_NM,HPSN_MCT_BZN_CD_NM,ARE_D,MCT_ME_D
0,000F03E44A,202404,4,5,5,5,5,1,-999999.9,2.6,...,6.0273,5.00,45.00,12.5,12.5,75.0,중식-딤섬/중식만두,뚝섬,20220225,NaN
1,000F03E44A,202312,4,6,6,6,6,NaN,-999999.9,0.0,...,0.0000,0.00,0.00,-999999.9,-999999.9,-999999.9,중식-딤섬/중식만두,뚝섬,20220225,NaN
2,002816BA73,202404,2,3,4,4,2,6,-999999.9,96.6,...,2.2352,10.66,6.12,23.8,23.8,52.4,요리주점,마장동,20140507,NaN
3,002816BA73,202411,2,3,4,4,2,6,-999999.9,108.0,...,3.3415,10.41,6.30,11.5,11.5,76.9,요리주점,마장동,20140507,NaN
4,002816BA73,202406,2,4,4,4,2,1,-999999.9,74.2,...,2.0480,9.86,4.69,13.0,17.4,69.6,요리주점,마장동,20140507,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86585,A2D9C941A9,202304,5,2,1,1,6,2,2.6,249.7,...,4.3371,43.31,10.15,71.3,4.3,24.4,커피전문점,NaN,20220823,NaN
86586,A7C2307794,202303,2,2,2,2,3,1,19.2,196.7,...,8.5137,19.29,8.75,36.8,7.4,55.9,한식-두부요리,옥수,20140508,NaN
86587,BF6A6456AB,202407,6,2,4,4,1,6,1.6,176.3,...,5.4627,18.24,12.94,16.7,41.7,41.7,한식-육류/고기,뚝섬,20240131,20250724.0
86588,C59F032CAC,202406,1,2,2,2,4,2,24.0,116.5,...,1.8656,28.92,7.88,40.0,11.3,48.7,샌드위치/토스트,한양대,20090421,NaN
86589,F46D45E328,202302,2,2,3,3,3,1,12.8,215.6,...,2.6640,31.16,4.15,25.0,25.0,50.0,중식당,답십리,20131128,NaN

In [ ]:
data_prep['HPSN_MCT_BZN_CD_NM'].fillna('비상권', inplace=True)

/tmp/ipython-input-1637789189.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data_prep['HPSN_MCT_BZN_CD_NM'].fillna('비상권', inplace=True)

In [ ]:
data_prep

,ENCODED_MCT,TA_YM,MCT_OPE_MS_CN,RC_M1_SAA,RC_M1_TO_UE_CT,RC_M1_UE_CUS_CN,RC_M1_AV_NP_AT,APV_CE_RAT,DLV_SAA_RAT,M1_SME_RY_SAA_RAT,...,M12_FME_60_RAT,MCT_UE_CLN_REU_RAT,MCT_UE_CLN_NEW_RAT,RC_M1_SHC_RSD_UE_CLN_RAT,RC_M1_SHC_WP_UE_CLN_RAT,RC_M1_SHC_FLP_UE_CLN_RAT,HPSN_MCT_ZCD_NM,HPSN_MCT_BZN_CD_NM,ARE_D,MCT_ME_D
0,000F03E44A,202404,4,5,5,5,5,1,-999999.9,2.6,...,6.0273,5.00,45.00,12.5,12.5,75.0,중식-딤섬/중식만두,뚝섬,20220225,NaN
1,000F03E44A,202312,4,6,6,6,6,NaN,-999999.9,0.0,...,0.0000,0.00,0.00,-999999.9,-999999.9,-999999.9,중식-딤섬/중식만두,뚝섬,20220225,NaN
2,002816BA73,202404,2,3,4,4,2,6,-999999.9,96.6,...,2.2352,10.66,6.12,23.8,23.8,52.4,요리주점,마장동,20140507,NaN
3,002816BA73,202411,2,3,4,4,2,6,-999999.9,108.0,...,3.3415,10.41,6.30,11.5,11.5,76.9,요리주점,마장동,20140507,NaN
4,002816BA73,202406,2,4,4,4,2,1,-999999.9,74.2,...,2.0480,9.86,4.69,13.0,17.4,69.6,요리주점,마장동,20140507,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86585,A2D9C941A9,202304,5,2,1,1,6,2,2.6,249.7,...,4.3371,43.31,10.15,71.3,4.3,24.4,커피전문점,비상권,20220823,NaN
86586,A7C2307794,202303,2,2,2,2,3,1,19.2,196.7,...,8.5137,19.29,8.75,36.8,7.4,55.9,한식-두부요리,옥수,20140508,NaN
86587,BF6A6456AB,202407,6,2,4,4,1,6,1.6,176.3,...,5.4627,18.24,12.94,16.7,41.7,41.7,한식-육류/고기,뚝섬,20240131,20250724.0
86588,C59F032CAC,202406,1,2,2,2,4,2,24.0,116.5,...,1.8656,28.92,7.88,40.0,11.3,48.7,샌드위치/토스트,한양대,20090421,NaN
86589,F46D45E328,202302,2,2,3,3,3,1,12.8,215.6,...,2.6640,31.16,4.15,25.0,25.0,50.0,중식당,답십리,20131128,NaN

In [ ]:
data_prep.to_csv('/content/drive/MyDrive/B.S.degree/Capstone2_HelloKitty/dataset/BasicData_Prep3.csv', encoding='cp949')

In [ ]:
data_prep = pd.read_csv('/content/drive/MyDrive/B.S.degree/Capstone2_HelloKitty/dataset/BasicData_Prep3.csv', encoding='cp949').drop(columns='Unnamed: 0').sort_values(by=['ENCODED_MCT', 'TA_YM'])
data_prep

,ENCODED_MCT,TA_YM,MCT_OPE_MS_CN,RC_M1_SAA,RC_M1_TO_UE_CT,RC_M1_UE_CUS_CN,RC_M1_AV_NP_AT,APV_CE_RAT,DLV_SAA_RAT,M1_SME_RY_SAA_RAT,...,M12_FME_60_RAT,MCT_UE_CLN_REU_RAT,MCT_UE_CLN_NEW_RAT,RC_M1_SHC_RSD_UE_CLN_RAT,RC_M1_SHC_WP_UE_CLN_RAT,RC_M1_SHC_FLP_UE_CLN_RAT,HPSN_MCT_ZCD_NM,HPSN_MCT_BZN_CD_NM,ARE_D,MCT_ME_D
46117,000F03E44A,202301,5,6,5,5,4,1.0,-999999.9,0.5,...,0.0000,0.00,100.00,0.0,0.0,100.0,중식-딤섬/중식만두,뚝섬,20220225,NaN
27145,000F03E44A,202302,5,6,6,6,6,NaN,-999999.9,0.0,...,0.0000,0.00,0.00,-999999.9,-999999.9,-999999.9,중식-딤섬/중식만두,뚝섬,20220225,NaN
27144,000F03E44A,202303,5,6,6,6,6,NaN,-999999.9,0.0,...,0.0000,0.00,0.00,-999999.9,-999999.9,-999999.9,중식-딤섬/중식만두,뚝섬,20220225,NaN
51842,000F03E44A,202304,5,6,5,5,3,1.0,-999999.9,1.3,...,0.0000,0.00,50.00,0.0,100.0,0.0,중식-딤섬/중식만두,뚝섬,20220225,NaN
34110,000F03E44A,202305,5,6,5,5,6,1.0,-999999.9,0.0,...,0.0000,0.00,33.33,0.0,0.0,100.0,중식-딤섬/중식만두,뚝섬,20220225,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81837,FFF0DAC445,202408,3,2,3,3,3,1.0,-999999.9,294.8,...,1.0695,9.60,6.24,16.0,20.8,63.2,꼬치구이,성수,20160704,NaN
19731,FFF0DAC445,202409,3,1,3,2,2,5.0,-999999.9,424.3,...,1.0120,9.62,8.07,21.5,16.2,62.3,꼬치구이,성수,20160704,NaN
34109,FFF0DAC445,202410,3,2,3,2,3,1.0,-999999.9,333.6,...,1.0741,10.27,7.48,16.8,16.0,67.2,꼬치구이,성수,20160704,NaN
40932,FFF0DAC445,202411,3,2,3,2,2,1.0,-999999.9,355.0,...,1.1450,10.28,7.96,17.9,19.5,62.6,꼬치구이,성수,20160704,NaN
86579,FFF0DAC445,202412,3,2,3,2,3,3.0,-999999.9,319.7,...,1.2908,10.41,7.68,24.0,15.7,60.3,꼬치구이,성수,20160704,NaN

In [ ]:
for c in data_prep.columns:
    nann = data_prep[c].isnull().sum()
    if nann != 0:
        print(f'{c} : {nann}/{86590} ({nann/86590})')

APV_CE_RAT : 6632/86590 (0.07659083034992493)
MCT_ME_D : 84256/86590 (0.9730453863032683)

In [ ]:
data_prep['MCT_ME_D'].unique()

array([      nan, 20250723., 20250819., 20250702., 20230417., 20250730.,
       20250714., 20250801., 20240521., 20250729., 20250811., 20250814.,
       20240903., 20250717., 20230504., 20250731., 20250728., 20250716.,
       20250805., 20250722., 20250407., 20230515., 20250708., 20230530.,
       20231031., 20230913., 20231113., 20250408., 20250721., 20250818.,
       20250707., 20250718., 20250808., 20250704., 20250710., 20240710.,
       20250107., 20241010., 20250820., 20230911., 20250703., 20230105.,
       20250725., 20250804., 20250514., 20230418., 20250806., 20240426.,
       20250822., 20240729., 20230821., 20250709., 20250610., 20250821.,
       20250117., 20240528., 20250724., 20240627., 20230822., 20231018.,
       20240514., 20241114., 20240402., 20250813., 20240102., 20250715.,
       20231127., 20240305., 20250214., 20241028., 20240808., 20250220.,
       20230321.])

In [ ]:
data_prep['ARE_D'] = pd.to_numeric(data_prep['ARE_D'], errors='coerce')
data_prep['MCT_ME_D'] = pd.to_numeric(data_prep['MCT_ME_D'], errors='coerce')

data_prep['ARE_D'] = data_prep['ARE_D'].astype('Int64')
data_prep['MCT_ME_D'] = data_prep['MCT_ME_D'].astype('Int64')

na_rows = data_prep['MCT_ME_D'].isna()
data_prep['survive'] = na_rows
data_prep

,ENCODED_MCT,TA_YM,MCT_OPE_MS_CN,RC_M1_SAA,RC_M1_TO_UE_CT,RC_M1_UE_CUS_CN,RC_M1_AV_NP_AT,APV_CE_RAT,DLV_SAA_RAT,M1_SME_RY_SAA_RAT,...,MCT_UE_CLN_REU_RAT,MCT_UE_CLN_NEW_RAT,RC_M1_SHC_RSD_UE_CLN_RAT,RC_M1_SHC_WP_UE_CLN_RAT,RC_M1_SHC_FLP_UE_CLN_RAT,HPSN_MCT_ZCD_NM,HPSN_MCT_BZN_CD_NM,ARE_D,MCT_ME_D,survive
46117,000F03E44A,202301,5,6,5,5,4,1.0,-999999.9,0.5,...,0.00,100.00,0.0,0.0,100.0,중식-딤섬/중식만두,뚝섬,20220225,<NA>,True
27145,000F03E44A,202302,5,6,6,6,6,NaN,-999999.9,0.0,...,0.00,0.00,-999999.9,-999999.9,-999999.9,중식-딤섬/중식만두,뚝섬,20220225,<NA>,True
27144,000F03E44A,202303,5,6,6,6,6,NaN,-999999.9,0.0,...,0.00,0.00,-999999.9,-999999.9,-999999.9,중식-딤섬/중식만두,뚝섬,20220225,<NA>,True
51842,000F03E44A,202304,5,6,5,5,3,1.0,-999999.9,1.3,...,0.00,50.00,0.0,100.0,0.0,중식-딤섬/중식만두,뚝섬,20220225,<NA>,True
34110,000F03E44A,202305,5,6,5,5,6,1.0,-999999.9,0.0,...,0.00,33.33,0.0,0.0,100.0,중식-딤섬/중식만두,뚝섬,20220225,<NA>,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81837,FFF0DAC445,202408,3,2,3,3,3,1.0,-999999.9,294.8,...,9.60,6.24,16.0,20.8,63.2,꼬치구이,성수,20160704,<NA>,True
19731,FFF0DAC445,202409,3,1,3,2,2,5.0,-999999.9,424.3,...,9.62,8.07,21.5,16.2,62.3,꼬치구이,성수,20160704,<NA>,True
34109,FFF0DAC445,202410,3,2,3,2,3,1.0,-999999.9,333.6,...,10.27,7.48,16.8,16.0,67.2,꼬치구이,성수,20160704,<NA>,True
40932,FFF0DAC445,202411,3,2,3,2,2,1.0,-999999.9,355.0,...,10.28,7.96,17.9,19.5,62.6,꼬치구이,성수,20160704,<NA>,True
86579,FFF0DAC445,202412,3,2,3,2,3,3.0,-999999.9,319.7,...,10.41,7.68,24.0,15.7,60.3,꼬치구이,성수,20160704,<NA>,True

In [ ]:
for idx in data_prep.index:
    tmp = data_prep.loc[idx]
    try:
        if tmp['TA_YM'] == tmp['MCT_ME_D']//100:
            data_prep.loc[idx, 'survive'] = 0
        else:
            data_prep.loc[idx, 'survive'] = 1
    except:
        data_prep.loc[idx, 'survive'] = 1

data_prep

/tmp/ipython-input-2165275645.py:9: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  data_prep.loc[idx, 'survive'] = 1

,ENCODED_MCT,TA_YM,MCT_OPE_MS_CN,RC_M1_SAA,RC_M1_TO_UE_CT,RC_M1_UE_CUS_CN,RC_M1_AV_NP_AT,APV_CE_RAT,DLV_SAA_RAT,M1_SME_RY_SAA_RAT,...,MCT_UE_CLN_REU_RAT,MCT_UE_CLN_NEW_RAT,RC_M1_SHC_RSD_UE_CLN_RAT,RC_M1_SHC_WP_UE_CLN_RAT,RC_M1_SHC_FLP_UE_CLN_RAT,HPSN_MCT_ZCD_NM,HPSN_MCT_BZN_CD_NM,ARE_D,MCT_ME_D,survive
46117,000F03E44A,202301,5,6,5,5,4,1.0,-999999.9,0.5,...,0.00,100.00,0.0,0.0,100.0,중식-딤섬/중식만두,뚝섬,20220225,<NA>,1
27145,000F03E44A,202302,5,6,6,6,6,NaN,-999999.9,0.0,...,0.00,0.00,-999999.9,-999999.9,-999999.9,중식-딤섬/중식만두,뚝섬,20220225,<NA>,1
27144,000F03E44A,202303,5,6,6,6,6,NaN,-999999.9,0.0,...,0.00,0.00,-999999.9,-999999.9,-999999.9,중식-딤섬/중식만두,뚝섬,20220225,<NA>,1
51842,000F03E44A,202304,5,6,5,5,3,1.0,-999999.9,1.3,...,0.00,50.00,0.0,100.0,0.0,중식-딤섬/중식만두,뚝섬,20220225,<NA>,1
34110,000F03E44A,202305,5,6,5,5,6,1.0,-999999.9,0.0,...,0.00,33.33,0.0,0.0,100.0,중식-딤섬/중식만두,뚝섬,20220225,<NA>,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81837,FFF0DAC445,202408,3,2,3,3,3,1.0,-999999.9,294.8,...,9.60,6.24,16.0,20.8,63.2,꼬치구이,성수,20160704,<NA>,1
19731,FFF0DAC445,202409,3,1,3,2,2,5.0,-999999.9,424.3,...,9.62,8.07,21.5,16.2,62.3,꼬치구이,성수,20160704,<NA>,1
34109,FFF0DAC445,202410,3,2,3,2,3,1.0,-999999.9,333.6,...,10.27,7.48,16.8,16.0,67.2,꼬치구이,성수,20160704,<NA>,1
40932,FFF0DAC445,202411,3,2,3,2,2,1.0,-999999.9,355.0,...,10.28,7.96,17.9,19.5,62.6,꼬치구이,성수,20160704,<NA>,1
86579,FFF0DAC445,202412,3,2,3,2,3,3.0,-999999.9,319.7,...,10.41,7.68,24.0,15.7,60.3,꼬치구이,성수,20160704,<NA>,1

In [ ]:
data_prep.loc[data_prep['ENCODED_MCT']=='1521FF7269']

,ENCODED_MCT,TA_YM,MCT_OPE_MS_CN,RC_M1_SAA,RC_M1_TO_UE_CT,RC_M1_UE_CUS_CN,RC_M1_AV_NP_AT,APV_CE_RAT,DLV_SAA_RAT,M1_SME_RY_SAA_RAT,...,MCT_UE_CLN_REU_RAT,MCT_UE_CLN_NEW_RAT,RC_M1_SHC_RSD_UE_CLN_RAT,RC_M1_SHC_WP_UE_CLN_RAT,RC_M1_SHC_FLP_UE_CLN_RAT,HPSN_MCT_ZCD_NM,HPSN_MCT_BZN_CD_NM,ARE_D,MCT_ME_D,survive
39512,1521FF7269,202301,5,4,4,4,3,1.0,84.6,52.6,...,11.70,8.30,42.9,7.1,50.0,한식-해물/생선,비상권,20220125,20240903,1
64062,1521FF7269,202302,5,4,4,4,3,1.0,83.4,47.5,...,9.81,7.55,33.3,0.0,66.7,한식-해물/생선,비상권,20220125,20240903,1
10531,1521FF7269,202303,5,4,4,4,3,1.0,82.9,45.8,...,9.82,7.64,29.2,4.2,66.7,한식-해물/생선,비상권,20220125,20240903,1
35075,1521FF7269,202304,5,4,4,4,3,1.0,75.9,57.9,...,10.68,8.90,39.3,0.0,60.7,한식-해물/생선,비상권,20220125,20240903,1
41059,1521FF7269,202305,5,3,4,3,3,5.0,71.6,78.7,...,11.11,14.81,25.5,4.3,70.2,한식-해물/생선,비상권,20220125,20240903,1
36643,1521FF7269,202306,5,4,4,4,3,1.0,75.2,60.6,...,9.94,8.97,28.1,3.1,68.8,한식-해물/생선,비상권,20220125,20240903,1
61067,1521FF7269,202307,5,3,4,4,3,1.0,73.8,74.6,...,11.48,11.18,31.8,6.8,61.4,한식-해물/생선,비상권,20220125,20240903,1
847,1521FF7269,202308,5,3,4,3,3,6.0,70.5,88.5,...,11.76,12.04,27.1,6.3,66.7,한식-해물/생선,비상권,20220125,20240903,1
845,1521FF7269,202309,5,3,4,3,3,1.0,68.4,94.0,...,11.14,12.73,36.0,10.0,54.0,한식-해물/생선,비상권,20220125,20240903,1
37925,1521FF7269,202310,4,3,4,4,3,6.0,75.6,75.0,...,11.60,8.51,32.5,5.0,62.5,한식-해물/생선,비상권,20220125,20240903,1
10533,1521FF7269,202311,4,4,4,4,3,6.0,78.1,67.8,...,12.02,6.65,15.4,3.8,80.8,한식-해물/생선,비상권,20220125,20240903,1
846,1521FF7269,202312,4,4,4,4,3,1.0,82.5,55.0,...,12.27,4.70,30.4,0.0,69.6,한식-해물/생선,비상권,20220125,20240903,1
80415,1521FF7269,202401,4,4,4,4,3,1.0,77.0,76.1,...,11.83,7.46,46.7,0.0,53.3,한식-해물/생선,비상권,20220125,20240903,1
844,1521FF7269,202402,4,4,4,4,3,1.0,81.1,52.4,...,12.40,4.13,30.0,5.0,65.0,한식-해물/생선,비상권,20220125,20240903,1
10532,1521FF7269,202403,4,4,4,4,3,1.0,79.5,55.5,...,13.25,4.94,45.8,0.0,54.2,한식-해물/생선,비상권,20220125,20240903,1
27242,1521FF7269,202404,4,4,4,4,3,6.0,85.0,38.6,...,12.96,4.50,31.8,0.0,68.2,한식-해물/생선,비상권,20220125,20240903,1
23564,1521FF7269,202405,4,4,4,4,3,1.0,76.6,44.5,...,13.56,5.08,52.9,0.0,47.1,한식-해물/생선,비상권,20220125,20240903,1
848,1521FF7269,202406,4,4,4,4,3,1.0,78.3,37.3,...,13.53,3.24,26.7,6.7,66.7,한식-해물/생선,비상권,20220125,20240903,1
18291,1521FF7269,202407,4,4,4,4,3,6.0,80.9,38.7,...,12.50,4.38,36.8,0.0,63.2,한식-해물/생선,비상권,20220125,20240903,1
32697,1521FF7269,202408,4,4,4,4,3,1.0,79.0,46.3,...,11.67,8.33,48.3,3.4,48.3,한식-해물/생선,비상권,20220125,20240903,1
75871,1521FF7269,202409,6,5,5,5,2,1.0,0.0,3.1,...,10.42,0.39,0.0,100.0,0.0,한식-해물/생선,비상권,20220125,20240903,0

In [ ]:
data_prep.loc[data_prep['ENCODED_MCT']=='000F03E44A']

,ENCODED_MCT,TA_YM,MCT_OPE_MS_CN,RC_M1_SAA,RC_M1_TO_UE_CT,RC_M1_UE_CUS_CN,RC_M1_AV_NP_AT,APV_CE_RAT,DLV_SAA_RAT,M1_SME_RY_SAA_RAT,...,MCT_UE_CLN_REU_RAT,MCT_UE_CLN_NEW_RAT,RC_M1_SHC_RSD_UE_CLN_RAT,RC_M1_SHC_WP_UE_CLN_RAT,RC_M1_SHC_FLP_UE_CLN_RAT,HPSN_MCT_ZCD_NM,HPSN_MCT_BZN_CD_NM,ARE_D,MCT_ME_D,survive
46117,000F03E44A,202301,5,6,5,5,4,1.0,-999999.9,0.5,...,0.00,100.00,0.0,0.0,100.0,중식-딤섬/중식만두,뚝섬,20220225,<NA>,1
27145,000F03E44A,202302,5,6,6,6,6,NaN,-999999.9,0.0,...,0.00,0.00,-999999.9,-999999.9,-999999.9,중식-딤섬/중식만두,뚝섬,20220225,<NA>,1
27144,000F03E44A,202303,5,6,6,6,6,NaN,-999999.9,0.0,...,0.00,0.00,-999999.9,-999999.9,-999999.9,중식-딤섬/중식만두,뚝섬,20220225,<NA>,1
51842,000F03E44A,202304,5,6,5,5,3,1.0,-999999.9,1.3,...,0.00,50.00,0.0,100.0,0.0,중식-딤섬/중식만두,뚝섬,20220225,<NA>,1
34110,000F03E44A,202305,5,6,5,5,6,1.0,-999999.9,0.0,...,0.00,33.33,0.0,0.0,100.0,중식-딤섬/중식만두,뚝섬,20220225,<NA>,1
49032,000F03E44A,202306,5,6,5,5,6,1.0,-999999.9,0.1,...,0.00,25.00,0.0,0.0,100.0,중식-딤섬/중식만두,뚝섬,20220225,<NA>,1
42387,000F03E44A,202307,5,6,6,6,6,NaN,-999999.9,0.0,...,0.00,0.00,-999999.9,-999999.9,-999999.9,중식-딤섬/중식만두,뚝섬,20220225,<NA>,1
18161,000F03E44A,202308,5,6,6,6,6,NaN,-999999.9,0.0,...,0.00,0.00,-999999.9,-999999.9,-999999.9,중식-딤섬/중식만두,뚝섬,20220225,<NA>,1
32547,000F03E44A,202309,5,6,5,5,5,1.0,-999999.9,0.3,...,0.00,20.00,0.0,0.0,100.0,중식-딤섬/중식만두,뚝섬,20220225,<NA>,1
12868,000F03E44A,202310,5,6,6,6,6,NaN,-999999.9,0.0,...,0.00,0.00,-999999.9,-999999.9,-999999.9,중식-딤섬/중식만두,뚝섬,20220225,<NA>,1
50508,000F03E44A,202311,4,6,5,5,6,1.0,-999999.9,0.0,...,0.00,16.67,0.0,0.0,100.0,중식-딤섬/중식만두,뚝섬,20220225,<NA>,1
1,000F03E44A,202312,4,6,6,6,6,NaN,-999999.9,0.0,...,0.00,0.00,-999999.9,-999999.9,-999999.9,중식-딤섬/중식만두,뚝섬,20220225,<NA>,1
21946,000F03E44A,202401,4,6,6,6,6,NaN,-999999.9,0.0,...,0.00,0.00,-999999.9,-999999.9,-999999.9,중식-딤섬/중식만두,뚝섬,20220225,<NA>,1
40933,000F03E44A,202402,4,6,5,5,6,1.0,-999999.9,0.1,...,0.00,28.57,0.0,0.0,100.0,중식-딤섬/중식만두,뚝섬,20220225,<NA>,1
40934,000F03E44A,202403,4,5,5,5,4,1.0,-999999.9,2.3,...,0.00,41.67,0.0,0.0,100.0,중식-딤섬/중식만두,뚝섬,20220225,<NA>,1
0,000F03E44A,202404,4,5,5,5,5,1.0,-999999.9,2.6,...,5.00,45.00,12.5,12.5,75.0,중식-딤섬/중식만두,뚝섬,20220225,<NA>,1
56331,000F03E44A,202405,4,5,5,5,4,1.0,-999999.9,6.3,...,3.57,32.14,0.0,25.0,75.0,중식-딤섬/중식만두,뚝섬,20220225,<NA>,1
63918,000F03E44A,202406,4,5,5,5,3,1.0,-999999.9,14.2,...,8.57,22.86,0.0,16.7,83.3,중식-딤섬/중식만두,뚝섬,20220225,<NA>,1
75757,000F03E44A,202407,4,6,5,5,5,1.0,77.5,0.7,...,8.11,5.41,50.0,0.0,50.0,중식-딤섬/중식만두,뚝섬,20220225,<NA>,1
74399,000F03E44A,202408,4,6,6,6,6,NaN,100.0,0.0,...,8.11,0.00,-999999.9,-999999.9,-999999.9,중식-딤섬/중식만두,뚝섬,20220225,<NA>,1
10375,000F03E44A,202409,4,5,5,5,2,6.0,15.5,8.8,...,10.26,7.69,0.0,50.0,50.0,중식-딤섬/중식만두,뚝섬,20220225,<NA>,1
27143,000F03E44A,202410,4,5,5,5,4,1.0,58.0,2.2,...,9.30,9.30,66.7,0.0,33.3,중식-딤섬/중식만두,뚝섬,20220225,<NA>,1
75756,000F03E44A,202411,4,6,5,5,5,1.0,86.7,0.3,...,9.30,2.33,0.0,0.0,100.0,중식-딤섬/중식만두,뚝섬,20220225,<NA>,1
75758,000F03E44A,202412,4,6,5,5,5,1.0,78.0,0.7,...,10.87,6.52,0.0,25.0,75.0,중식-딤섬/중식만두,뚝섬,20220225,<NA>,1

In [ ]:
def get_last_day_from_yyyymm(yyyymm):
    if pd.isna(yyyymm):
        return None
    y = int(yyyymm // 100)
    m = int(yyyymm % 100)
    d = calendar.monthrange(y, m)[1]
    return y * 10000 + m * 100 + d

replacement_dates = data_prep.loc[na_rows, 'TA_YM'].apply(get_last_day_from_yyyymm)

data_prep['MCT_ME_D'] = data_prep['MCT_ME_D'].fillna(replacement_dates)

date1_series = pd.to_datetime(data_prep['ARE_D'].astype(str), format='%Y%m%d', errors='coerce')
date2_series = pd.to_datetime(data_prep['MCT_ME_D'].astype(str), format='%Y%m%d', errors='coerce')

data_prep['day_diff'] = (date2_series - date1_series).dt.days.abs()

data_prep

,ENCODED_MCT,TA_YM,MCT_OPE_MS_CN,RC_M1_SAA,RC_M1_TO_UE_CT,RC_M1_UE_CUS_CN,RC_M1_AV_NP_AT,APV_CE_RAT,DLV_SAA_RAT,M1_SME_RY_SAA_RAT,...,MCT_UE_CLN_NEW_RAT,RC_M1_SHC_RSD_UE_CLN_RAT,RC_M1_SHC_WP_UE_CLN_RAT,RC_M1_SHC_FLP_UE_CLN_RAT,HPSN_MCT_ZCD_NM,HPSN_MCT_BZN_CD_NM,ARE_D,MCT_ME_D,survive,day_diff
46117,000F03E44A,202301,5,6,5,5,4,1.0,-999999.9,0.5,...,100.00,0.0,0.0,100.0,중식-딤섬/중식만두,뚝섬,20220225,20230131,1,340
27145,000F03E44A,202302,5,6,6,6,6,NaN,-999999.9,0.0,...,0.00,-999999.9,-999999.9,-999999.9,중식-딤섬/중식만두,뚝섬,20220225,20230228,1,368
27144,000F03E44A,202303,5,6,6,6,6,NaN,-999999.9,0.0,...,0.00,-999999.9,-999999.9,-999999.9,중식-딤섬/중식만두,뚝섬,20220225,20230331,1,399
51842,000F03E44A,202304,5,6,5,5,3,1.0,-999999.9,1.3,...,50.00,0.0,100.0,0.0,중식-딤섬/중식만두,뚝섬,20220225,20230430,1,429
34110,000F03E44A,202305,5,6,5,5,6,1.0,-999999.9,0.0,...,33.33,0.0,0.0,100.0,중식-딤섬/중식만두,뚝섬,20220225,20230531,1,460
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81837,FFF0DAC445,202408,3,2,3,3,3,1.0,-999999.9,294.8,...,6.24,16.0,20.8,63.2,꼬치구이,성수,20160704,20240831,1,2980
19731,FFF0DAC445,202409,3,1,3,2,2,5.0,-999999.9,424.3,...,8.07,21.5,16.2,62.3,꼬치구이,성수,20160704,20240930,1,3010
34109,FFF0DAC445,202410,3,2,3,2,3,1.0,-999999.9,333.6,...,7.48,16.8,16.0,67.2,꼬치구이,성수,20160704,20241031,1,3041
40932,FFF0DAC445,202411,3,2,3,2,2,1.0,-999999.9,355.0,...,7.96,17.9,19.5,62.6,꼬치구이,성수,20160704,20241130,1,3071
86579,FFF0DAC445,202412,3,2,3,2,3,3.0,-999999.9,319.7,...,7.68,24.0,15.7,60.3,꼬치구이,성수,20160704,20241231,1,3102

In [ ]:
data_prep.drop(columns=['ARE_D','MCT_ME_D'], inplace=True)
data_prep

,ENCODED_MCT,TA_YM,MCT_OPE_MS_CN,RC_M1_SAA,RC_M1_TO_UE_CT,RC_M1_UE_CUS_CN,RC_M1_AV_NP_AT,APV_CE_RAT,DLV_SAA_RAT,M1_SME_RY_SAA_RAT,...,M12_FME_60_RAT,MCT_UE_CLN_REU_RAT,MCT_UE_CLN_NEW_RAT,RC_M1_SHC_RSD_UE_CLN_RAT,RC_M1_SHC_WP_UE_CLN_RAT,RC_M1_SHC_FLP_UE_CLN_RAT,HPSN_MCT_ZCD_NM,HPSN_MCT_BZN_CD_NM,survive,day_diff
46117,000F03E44A,202301,5,6,5,5,4,1.0,-999999.9,0.5,...,0.0000,0.00,100.00,0.0,0.0,100.0,중식-딤섬/중식만두,뚝섬,1,340
27145,000F03E44A,202302,5,6,6,6,6,NaN,-999999.9,0.0,...,0.0000,0.00,0.00,-999999.9,-999999.9,-999999.9,중식-딤섬/중식만두,뚝섬,1,368
27144,000F03E44A,202303,5,6,6,6,6,NaN,-999999.9,0.0,...,0.0000,0.00,0.00,-999999.9,-999999.9,-999999.9,중식-딤섬/중식만두,뚝섬,1,399
51842,000F03E44A,202304,5,6,5,5,3,1.0,-999999.9,1.3,...,0.0000,0.00,50.00,0.0,100.0,0.0,중식-딤섬/중식만두,뚝섬,1,429
34110,000F03E44A,202305,5,6,5,5,6,1.0,-999999.9,0.0,...,0.0000,0.00,33.33,0.0,0.0,100.0,중식-딤섬/중식만두,뚝섬,1,460
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81837,FFF0DAC445,202408,3,2,3,3,3,1.0,-999999.9,294.8,...,1.0695,9.60,6.24,16.0,20.8,63.2,꼬치구이,성수,1,2980
19731,FFF0DAC445,202409,3,1,3,2,2,5.0,-999999.9,424.3,...,1.0120,9.62,8.07,21.5,16.2,62.3,꼬치구이,성수,1,3010
34109,FFF0DAC445,202410,3,2,3,2,3,1.0,-999999.9,333.6,...,1.0741,10.27,7.48,16.8,16.0,67.2,꼬치구이,성수,1,3041
40932,FFF0DAC445,202411,3,2,3,2,2,1.0,-999999.9,355.0,...,1.1450,10.28,7.96,17.9,19.5,62.6,꼬치구이,성수,1,3071
86579,FFF0DAC445,202412,3,2,3,2,3,3.0,-999999.9,319.7,...,1.2908,10.41,7.68,24.0,15.7,60.3,꼬치구이,성수,1,3102

In [ ]:
data_prep.to_csv('/content/drive/MyDrive/B.S.degree/Capstone2_HelloKitty/dataset/BasicData_Prep3.csv', encoding='cp949')

In [ ]:
data_prep2 = pd.read_csv('/content/drive/MyDrive/B.S.degree/Capstone2_HelloKitty/dataset/BasicData_Prep3.csv', encoding='cp949').drop(columns='Unnamed: 0').sort_values(by=['ENCODED_MCT', 'TA_YM'])
data_prep2

,ENCODED_MCT,TA_YM,MCT_OPE_MS_CN,RC_M1_SAA,RC_M1_TO_UE_CT,RC_M1_UE_CUS_CN,RC_M1_AV_NP_AT,APV_CE_RAT,DLV_SAA_RAT,M1_SME_RY_SAA_RAT,...,M12_FME_60_RAT,MCT_UE_CLN_REU_RAT,MCT_UE_CLN_NEW_RAT,RC_M1_SHC_RSD_UE_CLN_RAT,RC_M1_SHC_WP_UE_CLN_RAT,RC_M1_SHC_FLP_UE_CLN_RAT,HPSN_MCT_ZCD_NM,HPSN_MCT_BZN_CD_NM,survive,day_diff
0,000F03E44A,202301,5,6,5,5,4,1.0,-999999.9,0.5,...,0.0000,0.00,100.00,0.0,0.0,100.0,중식-딤섬/중식만두,뚝섬,1,340
1,000F03E44A,202302,5,6,6,6,6,NaN,-999999.9,0.0,...,0.0000,0.00,0.00,-999999.9,-999999.9,-999999.9,중식-딤섬/중식만두,뚝섬,1,368
2,000F03E44A,202303,5,6,6,6,6,NaN,-999999.9,0.0,...,0.0000,0.00,0.00,-999999.9,-999999.9,-999999.9,중식-딤섬/중식만두,뚝섬,1,399
3,000F03E44A,202304,5,6,5,5,3,1.0,-999999.9,1.3,...,0.0000,0.00,50.00,0.0,100.0,0.0,중식-딤섬/중식만두,뚝섬,1,429
4,000F03E44A,202305,5,6,5,5,6,1.0,-999999.9,0.0,...,0.0000,0.00,33.33,0.0,0.0,100.0,중식-딤섬/중식만두,뚝섬,1,460
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86585,FFF0DAC445,202408,3,2,3,3,3,1.0,-999999.9,294.8,...,1.0695,9.60,6.24,16.0,20.8,63.2,꼬치구이,성수,1,2980
86586,FFF0DAC445,202409,3,1,3,2,2,5.0,-999999.9,424.3,...,1.0120,9.62,8.07,21.5,16.2,62.3,꼬치구이,성수,1,3010
86587,FFF0DAC445,202410,3,2,3,2,3,1.0,-999999.9,333.6,...,1.0741,10.27,7.48,16.8,16.0,67.2,꼬치구이,성수,1,3041
86588,FFF0DAC445,202411,3,2,3,2,2,1.0,-999999.9,355.0,...,1.1450,10.28,7.96,17.9,19.5,62.6,꼬치구이,성수,1,3071
86589,FFF0DAC445,202412,3,2,3,2,3,3.0,-999999.9,319.7,...,1.2908,10.41,7.68,24.0,15.7,60.3,꼬치구이,성수,1,3102

In [ ]:
def quaters(x):
    mm = int(str(x['TA_YM'])[-2:])
    return ((mm-1) // 3) + 1

data_prep2['quaters'] = data_prep2.apply(quaters, axis=1)
data_prep2

,ENCODED_MCT,TA_YM,MCT_OPE_MS_CN,RC_M1_SAA,RC_M1_TO_UE_CT,RC_M1_UE_CUS_CN,RC_M1_AV_NP_AT,APV_CE_RAT,DLV_SAA_RAT,M1_SME_RY_SAA_RAT,...,MCT_UE_CLN_REU_RAT,MCT_UE_CLN_NEW_RAT,RC_M1_SHC_RSD_UE_CLN_RAT,RC_M1_SHC_WP_UE_CLN_RAT,RC_M1_SHC_FLP_UE_CLN_RAT,HPSN_MCT_ZCD_NM,HPSN_MCT_BZN_CD_NM,survive,day_diff,quaters
0,000F03E44A,202301,5,6,5,5,4,1.0,-999999.9,0.5,...,0.00,100.00,0.0,0.0,100.0,중식-딤섬/중식만두,뚝섬,1,340,1
1,000F03E44A,202302,5,6,6,6,6,NaN,-999999.9,0.0,...,0.00,0.00,-999999.9,-999999.9,-999999.9,중식-딤섬/중식만두,뚝섬,1,368,1
2,000F03E44A,202303,5,6,6,6,6,NaN,-999999.9,0.0,...,0.00,0.00,-999999.9,-999999.9,-999999.9,중식-딤섬/중식만두,뚝섬,1,399,1
3,000F03E44A,202304,5,6,5,5,3,1.0,-999999.9,1.3,...,0.00,50.00,0.0,100.0,0.0,중식-딤섬/중식만두,뚝섬,1,429,2
4,000F03E44A,202305,5,6,5,5,6,1.0,-999999.9,0.0,...,0.00,33.33,0.0,0.0,100.0,중식-딤섬/중식만두,뚝섬,1,460,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86585,FFF0DAC445,202408,3,2,3,3,3,1.0,-999999.9,294.8,...,9.60,6.24,16.0,20.8,63.2,꼬치구이,성수,1,2980,3
86586,FFF0DAC445,202409,3,1,3,2,2,5.0,-999999.9,424.3,...,9.62,8.07,21.5,16.2,62.3,꼬치구이,성수,1,3010,3
86587,FFF0DAC445,202410,3,2,3,2,3,1.0,-999999.9,333.6,...,10.27,7.48,16.8,16.0,67.2,꼬치구이,성수,1,3041,4
86588,FFF0DAC445,202411,3,2,3,2,2,1.0,-999999.9,355.0,...,10.28,7.96,17.9,19.5,62.6,꼬치구이,성수,1,3071,4
86589,FFF0DAC445,202412,3,2,3,2,3,3.0,-999999.9,319.7,...,10.41,7.68,24.0,15.7,60.3,꼬치구이,성수,1,3102,4

In [ ]:
data_prep2.to_csv('/content/drive/MyDrive/B.S.degree/Capstone2_HelloKitty/dataset/BasicData_Prep4.csv', encoding='cp949')